apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wiz-deploy
  name: wiz-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: wiz-deploy
  type: NodePort
status:
  loadBalancer: {}
